### ISSUE TITLE
A meeting already exists with that meeting ID

### ISSUE THREAD

**Issue by JulianKropp** [mconf/bigbluebot#38] opened 2022-04-04 14:58 UTC
hey,

When I try to let the bot join an existing room, the following error occurs:

```
INFO    2022-04-04T14:43:32.222Z Bots: 1
INFO    2022-04-04T14:43:32.224Z Life: 100 seconds
INFO    2022-04-04T14:43:32.224Z Creating meeting
ERROR   2022-04-04T14:43:32.280Z idNotUnique: A meeting already exists with that meeting ID.  Please use a different meeting ID.
```

run.js
```
const bigbluebot = require('bigbluebot');

const actions = async page => {
  await bigbluebot.chat.send(page);
};
bigbluebot.run(actions);
```

.env
```
# <string> BigBlueButton hostname.
BIGBLUEBOT_HOST='https://server.com/bigbluebutton/'

# <string> BigBlueButton secret.
BIGBLUEBOT_SECRET='SECRET'

# <string> Running BigBlueButton server version.
BIGBLUEBOT_VERSION='2.4'

# <string> Room name or meetingID the bot should join. Defaults to 'Demo Meeting'
BIGBLUEBOT_ROOM='ROOMID'

# <string> Attendee password. Defaults to 'ap'
BIGBLUEBOT_ATTENDEE_PW='146579'

# <string> Moderator password. Defaults to 'mp'
BIGBLUEBOT_MODERATOR_PW='idntöd'

# <number> Number of bots to spawn. Defaults to 1.
BIGBLUEBOT_BOTS=1

# <number> Time between bots to join (ms). Defaults to 2000.
BIGBLUEBOT_WAIT=1000

# <number> Bot life span (ms). Defaults to 60000.
BIGBLUEBOT_LIFE=100000

# <string> External browser path. Defaults to null.
# BIGBLUEBOT_BROWSER=''

# <string> Endpoint browser websocket. Defaults to null.
# BIGBLUEBOT_ENDPOINT=''

# <string> Endpoint authentication token. Defaults to null.
# BIGBLUEBOT_TOKEN=''

# <string> Log level. Defaults to 'info'.
# BIGBLUEBOT_LOG=''

# <boolean> Whether to ignore HTTPS errors during navigation. Defaults to false.
# BIGBLUEBOT_IGNORE_HTTPS_ERRORS=
```

**Comment by pedrobmarin** [comment] 2022-04-04 15:06
Hey @JulianKropp ,

Could you check if you are setting the correct passwords for both moderator and attendee?

**Comment by pedrobmarin** [comment] 2022-04-04 15:25
Hmmmm, which BigBlueButton version are you running?

**Comment by JulianKropp** [comment] 2022-04-04 16:24
I´m using BBB version 'BigBlueButton Server 2.4.5 (3021)'

The Bot can connect to the BBB server but it always tries to create a new room. Which works if the meetingID doesnt exist. If I set the BIGBLUEBOT_ROOM variable to an existing meetingID, the above error shows up.

**Comment by pedrobmarin** [comment] 2022-04-04 16:29
The only way I could reproduce this error was setting incorrect passwords for the existing room

**Comment by pedrobmarin** [comment] 2022-04-04 16:32
If you haven't tried yet, you could use https://mconf.github.io/api-mate to check your meeting info and match your settings

**Comment by pedrobmarin** [comment] 2022-04-04 17:08
It's not. Looks like you are getting the same error and the redirect to the home page is just a collateral effect of that. You get the same when using the default passwords for both users (`ap` and `mp`)?

**Comment by JulianKropp** [comment] 2022-04-04 17:12
Yes I do. Ok thanks for now. Tomorrow I will have a look at the BBB configuration.

**Comment by JulianKropp** [comment] 2022-04-05 07:26
The logs told me that the moderator and attendee passwords were wrong. I thought I had to use the password from greenlight. Which is wrong. The correct passwords for moderator and attendee are provided by a getMeetingInfo API request (https://mconf.github.io/api-mate).

However, it would be nice if the output could tell you that the password is wrong and not `A meeting already exists with that meeting ID.  Please use a different meeting ID.`

Thank you very much for your help

**Comment by pedrobmarin** [comment] 2022-04-05 10:53
I agree with you that this message it can be misleading and the only reason I had an idea about the problem you were facing was because I already had a similar one. But the error message displayed at the console comes from the BigBlueButton API response. So things need to change at BigBlueButton's side.

Closing this one for now.

**Closed by pedrobmarin** 2022-04-05 10:53 UTC
